GeekText_Team7/GeekText_Team7/Controllers/Api/BookAuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GeekText_Team7.Models;
using GeekText_Team7.Models.BookAuthorViewModels;

namespace GeekText_Team7.Controllers.Api
{
    public class BookAuthorsController : Controller
    {
        private readonly BookStoreSummer17Context _context;

        public BookAuthorsController(BookStoreSummer17Context context)
        {
            _context = context;    
        }

        
        public IActionResult Homepage()
        {
            return View();
        }

        [HttpGet]

        // GET: BookAuthors
        public async Task<IActionResult> Index(int id, string genre,int category, string search)
        {
            var viewModel = new BookIndexData();

            if (id == 1 && genre != null)
            {
                viewModel.Book = await _context.Book
                .Where(b => b.Genre.Equals(genre))
                .OrderBy(b => b.Title)
                .ToListAsync();

                viewModel.Author = await _context.Author
                .AsNoTracking()
                .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (id == 5 && genre != null)
            {
                viewModel.Book = await _context.Book
                .Where(b => b.Genre.Equals(genre))
                .OrderByDescending(b => b.Title)
                .ToListAsync();

                viewModel.Author = await _context.Author
                .AsNoTracking()
                .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (id == 1 && genre == null)
            {
                viewModel.Book = await _context.Book
                .OrderBy(b => b.Genre)
                .ToListAsync();

                viewModel.Author = await _context.Author
                .AsNoTracking()
                .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (id == 5 && genre == null)
            {
                viewModel.Book = await _context.Book
                .OrderByDescending(b => b.Genre)
                .ToListAsync();

                viewModel.Author = await _context.Author
                .AsNoTracking()
                .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (id == 2)
            {
                viewModel.Book = await _context.Book
                .OrderBy(b => b.Price)
                .AsNoTracking()
                .ToListAsync();

                viewModel.Author = await _context.Author
                .AsNoTracking()
                .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (id == 6)
            {
                viewModel.Book = await _context.Book
                .OrderByDescending(b => b.Price)
                .AsNoTracking()
                .ToListAsync();

                viewModel.Author = await _context.Author
                .AsNoTracking()
                .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (id == 3)
            {
                viewModel.Book = await _context.Book
                .OrderByDescending(b => b.Orders)
                .AsNoTracking()
                .ToListAsync();

                viewModel.Author = await _context.Author
                .AsNoTracking()
                .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (id == 7)
            {
                viewModel.Book = await _context.Book
                .OrderBy(b => b.Orders)
                .AsNoTracking()
                .ToListAsync();

                viewModel.Author = await _context.Author
                .AsNoTracking()
                .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (id == 4)
            {
                viewModel.Book = await _context.Book
                .OrderByDescending(b => b.TechValleyTimesOrders)
                .AsNoTracking()
                .ToListAsync();

                viewModel.Author = await _context.Author
                .AsNoTracking()
                .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (id == 8)
            {
                viewModel.Book = await _context.Book
                .OrderBy(b => b.TechValleyTimesOrders)
                .AsNoTracking()
                .ToListAsync();

                viewModel.Author = await _context.Author
                    .AsNoTracking()
                    .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (search != null)
            {

                if (category == 1)
                {
                    viewModel.Book = await _context.Book
                    .Where(b => b.Title.Contains(search))
                    .OrderBy(b => b.Title)
                    .ToListAsync();

                    viewModel.Author = await _context.Author
                   .ToListAsync();

                    viewModel.BookAuthor = await _context.BookAuthor
                        .Include(b => b.Author)
                        .Include(c => c.Book)
                        .ToListAsync();

                }
                else if (category == 2)
                {
                    viewModel.Book = await _context.Book
                    .Where(b => b.Genre.Contains(search))
                    .OrderBy(b => b.Title)
                    .ToListAsync();

                    viewModel.Author = await _context.Author
                   .ToListAsync();

                    viewModel.BookAuthor = await _context.BookAuthor
                        .Include(b => b.Author)
                        .Include(c => c.Book)
                        .ToListAsync();
                }
            }
            else
            {
                viewModel.Book = await _context.Book
                .OrderBy(b => b.Title)
                .AsNoTracking()
                .ToListAsync();

                viewModel.Author = await _context.Author
                    .AsNoTracking()
                    .ToListAsync();

                viewModel.BookAuthor = await _context.BookAuthor
                    .AsNoTracking()
                    .ToListAsync();
            }



            

            return View(viewModel);
        }

        public async Task<IActionResult> MostOrders()
        {
            var viewModel = new BookIndexData();

                viewModel.Book = await _context.Book
                .OrderByDescending(b => b.Orders)
                .AsNoTracking()
                .ToListAsync();

            return PartialView(viewModel);
        }

        public async Task<IActionResult> RecentlyAdded()
        {
            var viewModel = new BookIndexData();

            viewModel.Book = await _context.Book
                .OrderByDescending(b => b.Id)
                .AsNoTracking()
                .ToListAsync();

            return PartialView(viewModel);
        }

        public async Task<IActionResult> TVTBest()
        {
            var viewModel = new BookIndexData();

            viewModel.Book = await _context.Book
                .OrderByDescending(b => b.TechValleyTimesOrders)
                .AsNoTracking()
                .ToListAsync();

            return View(viewModel);
        }

        // GET: BookAuthors/Details/5
        public async Task<IActionResult> BookDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = new BookIndexData();

            viewModel.BookAuthor = await _context.BookAuthor
                .Include(c => c.Book)
                .Include(b => b.Author)
                .AsNoTracking()
                .ToListAsync();

            viewModel.Book = await _context.Book
                .Where(m => m.Id == id)
                .ToListAsync();

            viewModel.Author= await _context.Author
                .Include(c => c.BookAuthor)
                .AsNoTracking()
                .ToListAsync();


            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        // GET: BookAuthors/Details/5
        public async Task<IActionResult> AuthorDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = new BookIndexData();

            viewModel.BookAuthor = await _context.BookAuthor
                .Include(c => c.Book)
                .Include(b => b.Author)
                .AsNoTracking()
                .ToListAsync();

            viewModel.Author = await _context.Author
                .Where(m => m.Id == id)
                .ToListAsync();

GeekText_Team7/GeekText_Team7/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using GeekText_Team7.Models;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using GeekText_Team7.Data;

namespace GeekText_Team7.Controllers
{
    public class HomeController : Controller
    {

        private IConfigurationRoot _config;
        private ILogger<HomeController> _logger;

        public HomeController(IConfigurationRoot config, ILogger<HomeController> logger)
        {
            _config = config;
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Users()
        {
            return View();
        }

        public IActionResult Books()
        {
            return View();
        }

        public IActionResult Author()
        {
            return View();
        }

        public IActionResult BookAuthor()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }
        public IActionResult Cart()
        {
            return View();
        }

        public IActionResult SignUp()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }

        public IActionResult Biography()
        {
            ViewData["Message"] = "Your Biography page.";

            return View();
        }

    }
}

GeekText_Team7/GeekText_Team7/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Geek Text is an aspiring online book store that has tasked themselves with bringing the absolute best of Geek Culture to everyone. 
    Bringing together books from across all of Geek culture from textbooks for our students to Fantasy Novels and Graphic Novels for a more relaxed crowd, 
    Geek Text aims to expand these fantastic works to the world.<br /><br />
    
    Offering easy to find books through our advanced book browsing and easy to checkout shopping once registered, 
    Geek Text values the customers first and foremost and works to bring them the best experience posssible through our completely online bookstore.</p>

GeekText_Team7/GeekText_Team7/Views/Home/Cart.cshtml
@{
    ViewData["Title"] = "Cart";
}

<script>
function goBack() {
    window.history.back();
}
</script>

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <table id="cart" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th style="width:50%">Product</th>
                <th style="width:10%">Price</th>
                <th style="width:8%">Quantity</th>
                <th style="width:22%" class="text-center">Subtotal</th>
                <th style="width:10%"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td data-th="Product">
                    <div class="row">
                        <div class="col-sm-2 hidden-xs">@*Add Book Images*@<img src="" alt="..." class="img-responsive" /></div>
                        <div class="col-sm-10">
                            <h4 class="nomargin">@*Add Book Name from Database*@ Book 1</h4>
                            @*Add Book Descriptions*@<p>Book 1 Description</p>
                        </div>
                    </div>
                </td>
                @*Add Price from database*@<td data-th="Price"> Book Price</td>
                <td data-th="Quantity">
                    <input type="number" class="form-control text-center" value="1">
                </td>
                @*Subtotal*@<td data-th="Subtotal" class="text-center"> Subtotal</td>
                <td class="actions" data-th="">
                    <button class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button>
                    <button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr class="visible-xs">
                @*Add Total Price*@<td class="text-center"><strong>Total</strong></td>
            </tr>
            <tr>
                <td><a onclick="goBack()" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
                <td colspan="2" class="hidden-xs"></td>
                @*Add Total Price*@<td class="hidden-xs text-center"><strong>Total</strong></td>
                <td><a href="#" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
            </tr>
        </tfoot>
    </table>
</div>

GeekText_Team7/GeekText_Team7/Views/Home/Company Biography.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Insert short & sweet information on our "company" and this project.</p>

GeekText_Team7/GeekText_Team7/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
    
    <table>
        <tr>
            <th>Support Hours:</th>
            <th></th>
        </tr>
        <tr>
            <td>Monday:</td>
            <td>9am - 9pm</td>
        </tr>
        <tr>
            <td>Tuesday:</td>
            <td>9am - 9pm</td>
        </tr>
        <tr>
            <td>Wednesday:</td>
            <td>9am - 9pm</td>
        </tr>
        <tr>
            <td>Thursday:</td>
            <td>9am - 9pm</td>
        </tr>
        <tr>
            <td>Friday:</td>
            <td>9am - 9pm</td>
        </tr>
        <tr>
            <td>Saturday:</td>
            <td>9am - 12am</td>
        </tr>
        <tr>
            <td>Sunday:</td>
            <td>9am - 6pm</td>
        </tr>
    </table>

<br />

<address>
    <strong>Contact Information:</strong>
    <strong>Phone:</strong> 305.555.5555 <br />
    <strong>Support:</strong> <a href="mailto:mquir016@fiu.edu">Support@GeekText.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:mquir016@fiu.edu">Marketing@GeekText.com</a>
</address>

<address>
    <strong>Contact Address:</strong> <br />
    11200 SW 8th St<br />
    Miami, FL 33199<br />
</address>

GeekText_Team7/GeekText_Team7/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@*<iframe scrolling="no" frameborder="0" width="100%" height="350" src="http://localhost:61394/BookAuthors/MostOrders"></iframe>*@



<div class="row">
    <div class="col-lg-12">
        <a asp-controller="BookAuthors" asp-action="Index" class="btn btn-lg btn-success">Browse All Books</a>
    </div>
</div>

GeekText_Team7/GeekText_Team7/Views/Home/SignUp.cshtml
@{
    ViewData["Title"] = "Sign Up";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Sign Up</p>